### ISSUE TITLE
Not possible to define standard Svg and Path

### ISSUE THREAD

**Issue by grosmar** [back2dos/js-virtual-dom#17]
I've tried to define `svg` and `path` tags with their attributes, and it removes every custom attribute of path that I defined:

```haxe
static function svg(?attr:SvgAttr, ?children:Children):VNode return h('svg', attr, children);
static function path(?attr:PathAttr, ?children:Children):VNode return h('path', attr, children);
//...
typedef CheckboxAttr = {>Attr,
    @:optional var label(default,never):String;
    @:optional var disabled(default,never):Bool;
    @:optional var checked(default,never):Bool;
    @:optional var indeterminate(default,never):Bool;
    @:optional var value(default,never):String;
}

typedef SvgAttr = {>Attr,
    @:optional var xmlns:String;
    @:optional var externalResourcesRequired:Bool;
    @:optional var version:Float;
    @:optional var baseProfile:SvgBaseProfile;
    @:optional var width:Float;
    @:optional var height:Float;
    @:optional var preserveAspectRatio:String;
    @:optional var contentScriptType:String;
    @:optional var contentStyleType:String;
    @:optional var viewBox:String;
}

@:enum abstract SvgBaseProfile(String)
{
    var None = "none";
    var Full = "full";
    var Basic = "basic";
    var Tiny = "tiny";
}
```
hxx defined template:
```html
<svg class="mdc-checkbox__checkmark" viewBox="0 0 24 24">
    <path class="mdc-checkbox__checkmark__path"
        fill="none"
        stroke="white"
        d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
</svg>
```

Rendered result:
```html
<svg class="mdc-checkbox__checkmark">
    <path class="mdc-checkbox__checkmark__path"></path>
</svg>
```

Expected behavior:
I should see viewBox, fill, storke and d attributes in the rendered result

**Comment by back2dos** [comment]
That may be due to SVG not being HTML. IIRC virtual-dom has a way to create
nodes from other namespaces though.

**Comment by grosmar** [comment]
It's valid to put svg definitions inside html:
https://www.w3schools.com/html/html5_svg.asp

What is the way?

**Comment by back2dos** [comment]
That doesn't make SVG become HTML.

- `EventTarget` -> `Node` -> `Element` -> [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement)
- `EventTarget` -> `Node` -> `Element` -> [`SVGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement)

The problem is presumably that `document.createElement` creates HTML elements and therefore `document.createElementNS` is needed. In virtual-dom's hyperscript this is handled by a special `svg` function, which essentially just seems to [set a `namespace` on the properties](https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/svg.js#L24). You can try that, or you can define that `svg` function in the externs and use it instead of `h`.

That said, from my experience HTML and SVG don't mix all that well. If the SVG is static, my advice is to inline it in your CSS per data URI (most CSS preprocessors can [do that on the fly](http://lesscss.org/functions/#misc-functions-data-uri)) and then apply it as a background or something.

**Comment by grosmar** [comment]
Tried with that namespace. It has an effect, but unfortunately just new errors 😸 
`Cannot assign to read only property 'viewBox' of object '#<SVGSVGElement>'`

As I see those codes that should handle it properly are even not part of the dist.js (maybe I'm wrong)

**Comment by meefox** [comment]
as a workaround you can use raw content 
`<raw content=${'<svg>YOUR SVG</svg>'} />`

**Comment by back2dos** [comment]
Should be addressed here: https://github.com/haxetink/tink_domspec/issues/5
